<?php

class ReforgeTableSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		DB::table('reforges')->delete();
		
		Reforge::create(array('description' => "Increases Attack Distance",'name' => "Assault Slash Attack Distance"));
Reforge::create(array('description' => "Increases Damage",'name' => "Assault Slash Damage"));
Reforge::create(array('description' => "Decreases Cooldown",'name' => "Assault Slash Cooldown Decreased"));
Reforge::create(array('description' => "Increases Balance with Axes",'name' => "Axe Mastery Balance"));
Reforge::create(array('description' => "Increases Maximum Damage with Axes",'name' => "Axe Mastery Max Damage"));
Reforge::create(array('description' => "Increases Minimum Damage with Axes",'name' => "Axe Mastery Min Damage"));
Reforge::create(array('description' => "Increases Critical Rate with Axes",'name' => "Axe Mastery Critical"));
Reforge::create(array('description' => "Increases Balance with Blunts",'name' => "Blunt Mastery Balance"));
Reforge::create(array('description' => "Increases Maximum Damage with Blunts",'name' => "Blunt Mastery Max Damage"));
Reforge::create(array('description' => "Increases Maximum Damage with Blunts",'name' => "Blunt Mastery Max Damage"));
Reforge::create(array('description' => "Increases Minimum Damage with Blunts",'name' => "Blunt Mastery Min Damage"));
Reforge::create(array('description' => "Increases Critical Rate with Blunts",'name' => "Blunt Mastery Critical"));
Reforge::create(array('description' => "Increases Balance with Swords",'name' => "Sword Mastery Balance"));
Reforge::create(array('description' => "Increases Maximum Damage with Swords",'name' => "Sword Mastery Max Damage"));
Reforge::create(array('description' => "Increases Maximum Damage with Swords",'name' => "Sword Mastery Max Damage"));
Reforge::create(array('description' => "Increases Minimum Damage with Swords",'name' => "Sword Mastery Min Damage"));
Reforge::create(array('description' => "Increases Critical Rate with Swords",'name' => "Sword Mastery Critical"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Charge EXP"));
Reforge::create(array('description' => "Reduces damage taken from ranged attacks while Charging",'name' => "Charge Ranged Damage Reduction rate"));
Reforge::create(array('description' => "Enables the use of Charge without a shield",'name' => "Charge Able to charge without shields"));
Reforge::create(array('description' => "Increases Maximum Distance",'name' => "Charge Max Distance"));
Reforge::create(array('description' => "Decreases Minimum Range",'name' => "Charge Minimum Range"));
Reforge::create(array('description' => "Decreases Charge Cooldown Time",'name' => "Charge Cooldown Decreased"));
Reforge::create(array('description' => "Increases Maximum Damage",'name' => "Charge Damage"));
Reforge::create(array('description' => "Increases Balance with melee combat",'name' => "Combat Mastery Balance"));
Reforge::create(array('description' => "Increases Maximum Damage with melee combat",'name' => "Combat Mastery Max Damage"));
Reforge::create(array('description' => "Increases Minimum Damage with melee combat",'name' => "Combat Mastery Min Damage"));
Reforge::create(array('description' => "Increases Protection when Defense is active",'name' => "Defense Protection upon success"));
Reforge::create(array('description' => "Increases Defense when Defense is active",'name' => "Defense Defense Rate when successful"));
Reforge::create(array('description' => "Increases EXP Gained",'name' => "Defense EXP"));
Reforge::create(array('description' => "Decreases Evasion Cooldown Time",'name' => "Evasion Total Cooldown Limit"));
Reforge::create(array('description' => "Reduces Stamina Consumed upon evading",'name' => "Evasion Stamina Consumption"));
Reforge::create(array('description' => "Increases Maximum Teleport Distance with Final Hit",'name' => "Final Hit Teleport Distance"));
Reforge::create(array('description' => "Increases Final Hit Duration",'name' => "Final Hit Duration"));
Reforge::create(array('description' => "Increases Maximum Damage while using Final Hit",'name' => "Final Hit Max Damage"));
Reforge::create(array('description' => "Increases Minimum Damage while using Final Hit",'name' => "Final Hit Min Damage"));
Reforge::create(array('description' => "Decreases Final Hit Cooldown Time",'name' => "Final Hit Cooldown Decreased"));
Reforge::create(array('description' => "Increases Lance Charge Base Damage Rate",'name' => "Lance Charge Charge Damage"));
Reforge::create(array('description' => "Increases Lance Charge Base Damage Rate",'name' => "Lance Charge Charge Damage"));
Reforge::create(array('description' => "Increases Lance Charge Damage while Mounted",'name' => "Lance Charge Horseback Charge Damage"));
Reforge::create(array('description' => "Increases Lance Charge Radius while Mounted",'name' => "Lance Charge Horseback Charge Range Width"));
Reforge::create(array('description' => "Increases Lance Charge Maximum Distance while Mounted",'name' => "Lance Charge Horseback Charge Additional Distance of Charge"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Lance Charge EXP"));
Reforge::create(array('description' => "Increases Lance Charge Radius (For Humans and Elves)",'name' => "Lance Charge Human and Elf Charge Range Width"));
Reforge::create(array('description' => "Increases Lance Charge Radius (For Giants)",'name' => "Lance Charge Giant Charge Range Width"));
Reforge::create(array('description' => "Increases Lance Charge Damage on the Target",'name' => "Lance Charge Main Target Damage"));
Reforge::create(array('description' => "Increases Lance Charge Maximum Distance",'name' => "Lance Charge Max Distance"));
Reforge::create(array('description' => "Decreases Lance Charge Cooldown Time",'name' => "Lance Charge Cooldown Decreased"));
Reforge::create(array('description' => "Increases Returned Enemy Damage with Lance Counter",'name' => "Lance Counter Opponent Damage Reflection Rate"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Lance Counter EXP"));
Reforge::create(array('description' => "Increases Critical Damage with Lance Counter",'name' => "Lance Counter Critical Damage"));
Reforge::create(array('description' => "Increases Returned Enemy Damage with Counterattack",'name' => "Counterattack Opponent Damage Reflection Rate"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Counterattack EXP"));
Reforge::create(array('description' => "??",'name' => "Counterattack When successful, grants the use of the opponent's Attack Rate"));
Reforge::create(array('description' => "Increases Maximum Damage with Lances",'name' => "Lance Mastery Max Damage"));
Reforge::create(array('description' => "Increases Minimum Damage with Lances",'name' => "Lance Mastery Min Damage"));
Reforge::create(array('description' => "Increases Critical Rate with Lances",'name' => "Lance Mastery Critical"));
Reforge::create(array('description' => "Increases Smash Damage",'name' => "Smash Damage"));
Reforge::create(array('description' => "Increases Smash Damage",'name' => "Smash Damage"));
Reforge::create(array('description' => "Increases Smash Critical Rate",'name' => "Smash Critical Success"));
Reforge::create(array('description' => "Increases Stomp Range",'name' => "Stomp Attack Range"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Stomp EXP"));
Reforge::create(array('description' => "Increases Taunt Range",'name' => "Taunt Range"));
Reforge::create(array('description' => "Increases Aggro Duration",'name' => "Taunt Duration"));
Reforge::create(array('description' => "Increases Maximum Lurable Enemy CP",'name' => "Taunt Lure Enhancement"));
Reforge::create(array('description' => "Increases Maximum Lurable Enemy CP",'name' => "Taunt Lure Enhancement"));
Reforge::create(array('description' => "Increases Maximum Amount of Monsters Lured",'name' => "Taunt Max Monsters Lured"));
Reforge::create(array('description' => "Increases Maximum Amount of Monsters Lured",'name' => "Taunt Min Monsters Lured"));
Reforge::create(array('description' => "Increases Protection while Wind Guard is active",'name' => "Wind Guard Protection"));
Reforge::create(array('description' => "Increases Wind Guard Duration",'name' => "Wind Guard Duration"));
Reforge::create(array('description' => "Decreases Wind Guard Cooldown Time",'name' => "Wind Guard Cooldown Decreased"));
Reforge::create(array('description' => "Increases Windmill Range",'name' => "Windmill Attack Range"));
Reforge::create(array('description' => "Increases Windmill Damage",'name' => "Windmill Damage"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Windmill EXP"));
Reforge::create(array('description' => "Increases Maximum Range when using Arrow Revolver",'name' => "Arrow Revolver Range"));
Reforge::create(array('description' => "Increases Maximum Damage of Arrow Revolver",'name' => "Arrow Revolver Maximum Damage"));
Reforge::create(array('description' => "Increases Minimum Damage of Arrow Revolver",'name' => "Arrow Revolver Minimum Damage"));
Reforge::create(array('description' => "Increases damage of Crash Shot (Initial Shot)",'name' => "Crash Shot Projectile Damage"));
Reforge::create(array('description' => "Increases damage of Crash Shot (Initial Shot)",'name' => "Crash Shot Projectile Damage"));
Reforge::create(array('description' => "Increases Crash Shot Fragment Splash Range",'name' => "Crash Shot Max Fragment Range"));
Reforge::create(array('description' => "Increases Maximum Crash Shot Fragments",'name' => "Crash Shot Max Fragments"));
Reforge::create(array('description' => "Increases Crash Shot Fragment Damage",'name' => "Crash Shot Fragment Damage"));
Reforge::create(array('description' => "Increases Crash Shot Fragment Damage",'name' => "Crash Shot Fragment Damage"));
Reforge::create(array('description' => "Increases Maximum Damage with Crossbows",'name' => "Crossbow Mastery Max Damage"));
Reforge::create(array('description' => "Increases Minimum Damage with Crossbows",'name' => "Crossbow Mastery Min Damage"));
Reforge::create(array('description' => "Increases Minimum Damage with Crossbows",'name' => "Crossbow Mastery Min Damage"));
Reforge::create(array('description' => "Increases Critical Rate with Crossbows",'name' => "Crossbow Mastery Critical"));
Reforge::create(array('description' => "Increases Final Shot Duration",'name' => "Final Shot Duration"));
Reforge::create(array('description' => "Decreases Final Shot Cooldown Time",'name' => "Final Shot Cooldown Decreased"));
Reforge::create(array('description' => "Increases Magnum Shot Damage",'name' => "Magnum Shot Damage"));
Reforge::create(array('description' => "Increases Magnum Shot Damage",'name' => "Magnum Shot Damage"));
Reforge::create(array('description' => "Increases Maximum Damage with Bows",'name' => "Bow Mastery Max Damage"));
Reforge::create(array('description' => "Increases Maximum Damage with Bows",'name' => "Bow Mastery Max Damage"));
Reforge::create(array('description' => "Increases Minimum Damage with Bows",'name' => "Bow Mastery Min Damage"));
Reforge::create(array('description' => "Increases Balance of Ranged Attack",'name' => "Ranged Attack Ranged Attack Balance"));
Reforge::create(array('description' => "Increases Maximum Damage of Ranged Attack",'name' => "Ranged Attack Ranged Attack Max Damage"));
Reforge::create(array('description' => "Increases Maximum Damage of Ranged Attack",'name' => "Ranged Attack Ranged Attack Max Damage"));
Reforge::create(array('description' => "Increases Minimum Damage of Ranged Attack",'name' => "Ranged Attack Min Ranged Attack Damage"));
Reforge::create(array('description' => "Increases Aim Speed of Ranged Attack",'name' => "Ranged Attack Aim Speed"));
Reforge::create(array('description' => "Increases Maximum Range of Mirage Missile (Initial Shot)",'name' => "Mirage Missile Effect Range"));
Reforge::create(array('description' => "Increases Maximum Damage of Mirage Missile",'name' => "Mirage Missile Max Damage"));
Reforge::create(array('description' => "Increases Minimum Damage of Mirage Missile",'name' => "Mirage Missile Min Damage"));
Reforge::create(array('description' => "Increases Melee Damage Bonus of Support Shot",'name' => "Support Shot Damage"));
Reforge::create(array('description' => "Increases Melee Damage Bonus of Support Shot",'name' => "Support Shot Damage"));
Reforge::create(array('description' => "Increases Damage of Throwing Attack",'name' => "Throwing Attack Damage"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Throwing Attack EXP"));
Reforge::create(array('description' => "Increases minimum damage of Gold Strike",'name' => "Gold Strike Min Damage"));
Reforge::create(array('description' => "Increases maximum damage of Gold Strike",'name' => "Gold Strike Max Damage"));
Reforge::create(array('description' => "Increases Success Rate of Blacksmithing",'name' => "Blacksmithing Success Rate"));
Reforge::create(array('description' => "Increases Success Rate of Blacksmithing",'name' => "Blacksmithing Success Rate"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Blacksmithing EXP"));
Reforge::create(array('description' => "Increases Food Effect Duration(Only applies to food cooked while the reforged equipment is equipped)",'name' => "Cooking Effect Duration"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Cooking EXP"));
Reforge::create(array('description' => "Increases Food Quality",'name' => "Cooking Quality Bonus"));
Reforge::create(array('description' => "Increases Success Rate of Handicraft",'name' => "Handicraft Success Rate"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Handicraft EXP"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Metallurgy EXP"));
Reforge::create(array('description' => "Increases Success Rate of Metallurgy",'name' => "Metallurgy Success Rate"));
Reforge::create(array('description' => "Increases Success Rate of Metallurgy",'name' => "Metallurgy Success Rate"));
Reforge::create(array('description' => "Increases maximum amount of material gathered",'name' => "Metallurgy Amount gathered per attempt"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Tailoring EXP"));
Reforge::create(array('description' => "Increases Success Rate of Tailoring",'name' => "Tailoring Success Rate"));
Reforge::create(array('description' => "Increases Success Rate of Tailoring",'name' => "Tailoring Success Rate"));
Reforge::create(array('description' => "Increases Tailored Item Quality",'name' => "Tailoring Quality Bonus"));
Reforge::create(array('description' => "Increases Tailored Item Quality",'name' => "Tailoring Quality Bonus"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Carpentry EXP Bonus"));
Reforge::create(array('description' => "Increases Carpentry Success Rate while Chopping Wood",'name' => "Carpentry Wood Chopping Success Rate"));
Reforge::create(array('description' => "Increases Carpentry Success Rate while Chopping Wood",'name' => "Carpentry Wood Chopping Success Rate"));
Reforge::create(array('description' => "Increases Maximum Quality of crafted Bows",'name' => "Carpentry Max Bow Quality Bonus"));
Reforge::create(array('description' => "Increases Minimum Quality of Crafted Bows",'name' => "Carpentry Min Bow Quality Bonus"));
Reforge::create(array('description' => "Decreases Amount of Time to Craft Bows",'name' => "Carpentry Bow Production Time"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Fishing EXP"));
Reforge::create(array('description' => "Increases Chance of Fish Biting",'name' => "Fishing Chance to Lure"));
Reforge::create(array('description' => "Increases Success Rate of Automatic Fishing",'name' => "Fishing Automatic Fishing Success Rate"));
Reforge::create(array('description' => "Increases Catch Size of Automatic Fishing",'name' => "Fishing Automatic Fishing Catch Size"));
Reforge::create(array('description' => "Increases Catch Size of Fishes",'name' => "Fishing Fish Size"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Herbalism EXP"));
Reforge::create(array('description' => "Increases Success Rate of Refining",'name' => "Refining Success Rate"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Refining EXP"));
Reforge::create(array('description' => "Increases Range of Taming Wild Animals",'name' => "Taming Wild Animals Range"));
Reforge::create(array('description' => "Increases Success Rate of Taming Wild Animals",'name' => "Taming Wild Animals Success Rate"));
Reforge::create(array('description' => "Increases Taming Duration",'name' => "Taming Wild Animals Duration"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Taming Wild Animals EXP"));
Reforge::create(array('description' => "Increases Success Rate of Weaving",'name' => "Weaving Success Rate"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Weaving EXP"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Production Mastery EXP"));
Reforge::create(array('description' => "Increases Blaze Explosion Damage",'name' => "Blaze Explosion Damage"));
Reforge::create(array('description' => "Increases Blaze Damage(Initial Blow)",'name' => "Blaze Damage"));
Reforge::create(array('description' => "Increases Blaze Damage(Initial Blow)",'name' => "Blaze Damage"));
Reforge::create(array('description' => "Increases Blaze Explosion Radius",'name' => "Blaze Explosion Radius"));
Reforge::create(array('description' => "Increases Damage of Bolt Magics",'name' => "Bolt Mastery Damage"));
Reforge::create(array('description' => "Increases Damage of Bolt Magics",'name' => "Bolt Mastery Damage"));
Reforge::create(array('description' => "Increases Damage of Fire Magics",'name' => "Fire Mastery Damage"));
Reforge::create(array('description' => "Increases Damage of Fire Magics",'name' => "Fire Mastery Damage"));
Reforge::create(array('description' => "Increases Fire Shield Duration",'name' => "Fire Shield Duration"));
Reforge::create(array('description' => "Decreases Fire Shield Cooldown Time",'name' => "Fire Shield Cooldown Decreased"));
Reforge::create(array('description' => "Increases Damage of Fusion Bolt",'name' => "Fusion Bolt Damage"));
Reforge::create(array('description' => "Increases Damage of Fusion Bolt",'name' => "Fusion Bolt Damage"));
Reforge::create(array('description' => "Increases HP healed by Healing",'name' => "Healing HP Recovery"));
Reforge::create(array('description' => "Increases HP healed by Healing",'name' => "Healing HP Recovery"));
Reforge::create(array('description' => "Increases Damage of Ice Magics",'name' => "Ice Mastery Damage"));
Reforge::create(array('description' => "Increases Damage of Ice Magics",'name' => "Ice Mastery Damage"));
Reforge::create(array('description' => "Increases Duration of Ice Shield",'name' => "Ice Shield Duration"));
Reforge::create(array('description' => "Decreases Ice Shield Cooldown Time",'name' => "Ice Shield Cooldown Decreased"));
Reforge::create(array('description' => "Increases Damage of Lightning Magics",'name' => "Lightning Mastery Damage"));
Reforge::create(array('description' => "Increases Damage of Lightning Magics",'name' => "Lightning Mastery Damage"));
Reforge::create(array('description' => "Increases Duration of Lightning Shield",'name' => "Lightning Shield Duration"));
Reforge::create(array('description' => "Decreases Lightning Shield Cooldown Time",'name' => "Lightning Shield Cooldown"));
Reforge::create(array('description' => "Increases Mana Shield Mana Efficiency",'name' => "Mana Shield Damage Reduction Rate"));
Reforge::create(array('description' => "Increases Meditation MP Regeneration Rate",'name' => "Meditation MP Regeneration Rate"));
Reforge::create(array('description' => "Increases damage on Meteor's Impact",'name' => "Meteor Strike Impact"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Fireball EXP"));
Reforge::create(array('description' => "Increases Maximum Damage of Fireball",'name' => "Fireball Max Damage"));
Reforge::create(array('description' => "Increases Minimum Damage of Fireball",'name' => "Fireball Min Damage"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Firebolt EXP"));
Reforge::create(array('description' => "Increases Maximum Damage of Firebolt",'name' => "Firebolt Max Damage"));
Reforge::create(array('description' => "Increases Maximum Damage of Firebolt",'name' => "Firebolt Max Damage"));
Reforge::create(array('description' => "Increases Maximum Damage of Firebolt",'name' => "Firebolt Max Damage"));
Reforge::create(array('description' => "Increases Minimum Damage of Firebolt",'name' => "Firebolt Min Damage"));
Reforge::create(array('description' => "Increases Minimum Damage of Firebolt",'name' => "Firebolt Min Damage"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Hail Storm EXP"));
Reforge::create(array('description' => "Increases Range of Hail Storm",'name' => "Hail Storm Range"));
Reforge::create(array('description' => "Increases Maximum Damage of Hail Storm",'name' => "Hail Storm Max Damage"));
Reforge::create(array('description' => "Increases Minimum Damage of Hail Storm",'name' => "Hail Storm Min Damage"));
Reforge::create(array('description' => "Increases EXP gain",'name' => "Icebolt EXP"));
Reforge::create(array('description' => "Increases Maximum Damage of Icebolt",'name' => "Icebolt Max Damage"));
Reforge::create(array('description' => "Increases Maximum Damage of Icebolt",'name' => "Icebolt Max Damage"));
Reforge::create(array('description' => "Increases Maximum Damage of Icebolt",'name' => "Icebolt Max Damage"));
Reforge::create(array('description' => "Increases Minimum Damage of Icebolt",'name' => "Icebolt Min Damage"));
Reforge::create(array('description' => "Increases Minimum Damage of Icebolt",'name' => "Icebolt Min Damage"));
Reforge::create(array('description' => "Increases Minimum Damage of Icebolt",'name' => "Icebolt Min Damage"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Ice Spear EXP"));
Reforge::create(array('description' => "Increases Maximum Damage of Ice Spear",'name' => "Ice Spear Max Damage"));
Reforge::create(array('description' => "Increases Minimum Damage of Ice Spear",'name' => "Ice Spear Min Damage"));
Reforge::create(array('description' => "Increases AoE Radius of Ice Spear",'name' => "Ice Spear Attack Radius"));
Reforge::create(array('description' => "Increases Explosion Range of Ice Spear",'name' => "Ice Spear Explosion Range"));
Reforge::create(array('description' => "Increases Explosion Range of Ice Spear",'name' => "Ice Spear Explosion Range"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Lightning Bolt EXP"));
Reforge::create(array('description' => "Increases Wand Effectiveness?",'name' => "Lightning Bolt Wand Effectiveness"));
Reforge::create(array('description' => "Increases Wand Effectiveness?",'name' => "Lightning Bolt Wand Effectiveness"));
Reforge::create(array('description' => "Increases Maximum Damage of Lightning Bolt",'name' => "Lightning Bolt Max Damage"));
Reforge::create(array('description' => "Increases Maximum Damage of Lightning Bolt",'name' => "Lightning Bolt Max Damage"));
Reforge::create(array('description' => "Increases Maximum Damage of Lightning Bolt",'name' => "Lightning Bolt Max Damage"));
Reforge::create(array('description' => "Increases Maximum Damage of Lightning bolt",'name' => "Lightning Bolt Max Damage"));
Reforge::create(array('description' => "Increases Maximum Damage of Lightning Bolt",'name' => "Lightning Bolt Min Damage"));
Reforge::create(array('description' => "Increases Minimum Damage of Lightning bolt",'name' => "Lightning Bolt Min Damage"));
Reforge::create(array('description' => "Increases Duration of Natural Shield",'name' => "Natural Shield Duration"));
Reforge::create(array('description' => "Decreases Natural Shield Cooldown Time",'name' => "Natural Shield Cooldown Decreased"));
Reforge::create(array('description' => "Increases Defense of Party Healing",'name' => "Party Healing Defense"));
Reforge::create(array('description' => "Increases Defense of Party Healing",'name' => "Party Healing Defense"));
Reforge::create(array('description' => "Increases HP healed by Party Healing",'name' => "Party Healing HP Recovery"));
Reforge::create(array('description' => "Increases HP healed by Party Healing",'name' => "Party Healing HP Recovery"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Thunder EXP"));
Reforge::create(array('description' => "Increases Maximum Damage of Thunder",'name' => "Thunder Max Damage"));
Reforge::create(array('description' => "Increases Minimum Damage of Thunder",'name' => "Thunder Min Damage"));
Reforge::create(array('description' => "Increases balance of Magic-type skills",'name' => "Magic Mastery Balance"));
Reforge::create(array('description' => "Increases Barrier Spikes Max HP",'name' => "Barrier Spikes Max HP"));
Reforge::create(array('description' => "Increases Barrier Spikes Duration",'name' => "Barrier Spikes Duration"));
Reforge::create(array('description' => "Increases efficiency of Clay-type Alchemy",'name' => "Clay Alchemy Efficiency"));
Reforge::create(array('description' => "Increases efficiency of Fire-type Alchemy",'name' => "Fire Alchemy Efficiency"));
Reforge::create(array('description' => "Increases Flame Burst Attack Range",'name' => "Flame Burst Attack Range"));
Reforge::create(array('description' => "Increases Flame Burst Stun Duration",'name' => "Flame Burst Stun Duration"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Flame Burst EXP"));
Reforge::create(array('description' => "Increases Flame Burst Duration",'name' => "Flame Burst Duration"));
Reforge::create(array('description' => "Increases Maximum Damage of Flame Burst",'name' => "Flame Burst Max Damage"));
Reforge::create(array('description' => "Increases Minimum Damage of Flame Burst",'name' => "Flame Burst Min Damage"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Fragmentation EXP"));
Reforge::create(array('description' => "Increases the duration of Frozen Blast",'name' => "Frozen Blast Duration"));
Reforge::create(array('description' => "Increases the angle of Frozen Blast",'name' => "Frozen Blast Angle"));
Reforge::create(array('description' => "Increases Maximum Damage of Heat Buster",'name' => "Heat Buster Max Damage"));
Reforge::create(array('description' => "Increases Minimum Damage of Heat Buster",'name' => "Heat Buster Min Damage"));
Reforge::create(array('description' => "Increases HP Absorbed by Life Drain",'name' => "Life Drain Life Absorbed"));
Reforge::create(array('description' => "Increases Knockback Damage of Life Drain",'name' => "Life Drain Damage"));
Reforge::create(array('description' => "Increases CP limit of Sand Burst",'name' => "Sand Burst Blindness Enhancement"));
Reforge::create(array('description' => "Increases maximum duration of blindness",'name' => "Sand Burst Max Blindness Duration"));
Reforge::create(array('description' => "Increases minimum duration of blindness",'name' => "Sand Burst Min Blindness Duration"));
Reforge::create(array('description' => "Increases maximum damage of Sand Burst",'name' => "Sand Burst Max Damage"));
Reforge::create(array('description' => "Increases minimum damage of Sand Burst",'name' => "Sand Burst Min Damage"));
Reforge::create(array('description' => "Increases range of Water Cannon",'name' => "Water Cannon Range"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Water Cannon EXP"));
Reforge::create(array('description' => "Increases maximum damage of Water Cannon",'name' => "Water Cannon Max Damage"));
Reforge::create(array('description' => "Increases minimum damage of Water Cannon",'name' => "Water Cannon Min Damage"));
Reforge::create(array('description' => "Increases range of Wind Blast",'name' => "Wind Blast Range"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Wind Blast EXP"));
Reforge::create(array('description' => "Increases maximum damage of Wind Blast",'name' => "Wind Blast Max Damage"));
Reforge::create(array('description' => "Increases minimum damage of Wind Blast",'name' => "Wind Blast Min Damage"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Metal Conversion EXP"));
Reforge::create(array('description' => "Increases duration of Rain Casting",'name' => "Rain Casting Cloud Duration"));
Reforge::create(array('description' => "Increases cloud size of Rain Casting",'name' => "Rain Casting Cloud Range"));
Reforge::create(array('description' => "Decreases cooldown time of Rain Casting",'name' => "Rain Casting Cooldown Decreased"));
Reforge::create(array('description' => "Increases Water Cannon damage under a cloud",'name' => "Rain Casting Water Cannon Damage"));
Reforge::create(array('description' => "Increases maximum damage of Shock",'name' => "Shock Max Damage"));
Reforge::create(array('description' => "Increases maximum damage of Shock",'name' => "Shock Max Damage"));
Reforge::create(array('description' => "Increases minimum damage of Shock",'name' => "Shock Min Damage"));
Reforge::create(array('description' => "Increases stun duration of Shock",'name' => "Shock Stun Duration"));
Reforge::create(array('description' => "Increases range of Shock",'name' => "Shock Range"));
Reforge::create(array('description' => "Increases duration of Shock",'name' => "Shock Effect Duration"));
Reforge::create(array('description' => "Increases Max HP of summoned golems",'name' => "Summon Golem Golem Max HP"));
Reforge::create(array('description' => "Increases duration of summoned golems",'name' => "Summon Golem Golem Summon Duration"));
Reforge::create(array('description' => "Increases damage of summoned golems",'name' => "Summon Golem Golem Damage"));
Reforge::create(array('description' => "Increases defense of summoned golems",'name' => "Summon Golem Golem Defense"));
Reforge::create(array('description' => "Increases protection of summoned golems",'name' => "Summon Golem Golem Protection"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Summon Golem EXP"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Synthesis EXP"));
Reforge::create(array('description' => "Increases efficiency of Water-type Alchemy",'name' => "Water Alchemy Efficiency"));
Reforge::create(array('description' => "Increases efficiency of Wind-type Alchemy",'name' => "Wind Alchemy Efficiency"));
Reforge::create(array('description' => "Increases efficiency of Wind-type Alchemy",'name' => "Wind Alchemy Efficiency"));
Reforge::create(array('description' => "Increases minimum damage with knuckle-type weapons",'name' => "Knuckle Mastery Min Damage"));
Reforge::create(array('description' => "Increases maximum damage with knuckle-type weapons",'name' => "Knuckle Mastery Max Damage"));
Reforge::create(array('description' => "Increases balance with knuckle-type weapons",'name' => "Knuckle Mastery Balance"));
Reforge::create(array('description' => "Increases damage of Focused Fist",'name' => "Focused Fist Damage"));
Reforge::create(array('description' => "Decreases cooldown time of Focused Fist",'name' => "Focused Fist Cooldown Decreased"));
Reforge::create(array('description' => "Decreases charge time of Focused Fist",'name' => "Focused Fist Charge Time Reduction"));
Reforge::create(array('description' => "Increases range of Focused Fist",'name' => "Focused Fist Charge Range"));
Reforge::create(array('description' => "Increases damage of Spinning Uppercut",'name' => "Spinning Uppercut Damage Increase"));
Reforge::create(array('description' => "Decreases cooldown time of Spinning Uppercut",'name' => "Spinning Uppercut Cooldown Decreased"));
Reforge::create(array('description' => "Adds toward to defense reduction",'name' => "Spinning Uppercut Defense Reduction"));
Reforge::create(array('description' => "Increases protection reduction of Spinning Uppercut",'name' => "Spinning Uppercut Protection Reduction"));
Reforge::create(array('description' => "Increases status reduction chance of Spinning Uppercut",'name' => "Spinning Uppercut Defense/Protection Reduction Chance"));
Reforge::create(array('description' => "Increases damage of Somersault Kick",'name' => "Somersault Kick Damage"));
Reforge::create(array('description' => "Decreases cooldown time of Somersault Kick",'name' => "Somersault Kick Cooldown Decreased"));
Reforge::create(array('description' => "Increases debuff duration of Somersault Kick",'name' => "Somersault Kick Daze Duration"));
Reforge::create(array('description' => "Increases debuff chance of Somersault Kick",'name' => "Somersault Kick Daze Chance"));
Reforge::create(array('description' => "Increases damage of Drop Kick(Initial Hit)",'name' => "Drop Kick Damage"));
Reforge::create(array('description' => "Reduces cooldown time of Drop Kick",'name' => "Drop Kick Cooldown Decreased"));
Reforge::create(array('description' => "Increases linear radius of Drop Kick*Despite the name of the reforge, it affects the linear radius of Drop Kick",'name' => "Drop Kick Splash Range*"));
Reforge::create(array('description' => "Increases splash range of Drop Kick",'name' => "Drop Kick Splash Range"));
Reforge::create(array('description' => "Increases splash damage of Drop Kick",'name' => "Drop Kick Splash Damage"));
Reforge::create(array('description' => "Increases HP recovered per second of Respite",'name' => "Respite HP Recovery"));
Reforge::create(array('description' => "Increases Stamina recovered per second of Respite",'name' => "Respite Stamina Recovery"));
Reforge::create(array('description' => "Increases damage of Charging Strike",'name' => "Charging Strike Damage"));
Reforge::create(array('description' => "Decreases cooldown time of Charging Strike",'name' => "Charging Strike Cooldown Decreased"));
Reforge::create(array('description' => "Increases range of Charging Strike",'name' => "Charging Strike Range"));
Reforge::create(array('description' => "Increases damage of Pummel",'name' => "Pummel Damage"));
Reforge::create(array('description' => "Decreases cooldown time of Pummel",'name' => "Pummel Cooldown Decreased"));
Reforge::create(array('description' => "Increases number of punches in the first set",'name' => "Pummel Hits"));
Reforge::create(array('description' => "Increases number of punches in the second set",'name' => "Pummel Additional Hits"));
Reforge::create(array('description' => "Increases damage of Chain-related Skills",'name' => "Chain Mastery Damage"));
Reforge::create(array('description' => "Increases debuff duration of Dischord",'name' => "Dischord Debuff Duration"));
Reforge::create(array('description' => "Increases debuff duration of Dischord",'name' => "Dischord Debuff Duration"));
Reforge::create(array('description' => "Increases Splash radius of Dischord",'name' => "Dischord Effect Radius"));
Reforge::create(array('description' => "Increases damage of Dischord(Initial Hit)",'name' => "Dischord Instant Damage"));
Reforge::create(array('description' => "Increases damage of Dischord(Initial Hit)",'name' => "Dischord Instant Damage"));
Reforge::create(array('description' => "Increases continuous damage of Dischord",'name' => "Dischord Continuous Damage"));
Reforge::create(array('description' => "Increases continuous damage of Dischord",'name' => "Dischord Continuous Damage"));
Reforge::create(array('description' => "Increases movement speed debuff of Dischord",'name' => "Dischord Movement Speed Down"));
Reforge::create(array('description' => "Increases movement speed debuff of Dischord",'name' => "Dischord Movement Speed Down"));
Reforge::create(array('description' => "Increases duration of Battlefield Overture",'name' => "Battlefield Overture Duration"));
Reforge::create(array('description' => "Increases duration of Battlefield Overture",'name' => "Battlefield Overture Duration"));
Reforge::create(array('description' => "Increases radius of Battlefield Overture",'name' => "Battlefield Overture Effect Radius"));
Reforge::create(array('description' => "Increases radius of Battlefield Overture",'name' => "Battlefield Overture Effect Radius"));
Reforge::create(array('description' => "Increases duration of Enduring Melody",'name' => "Enduring Melody Effect Duration"));
Reforge::create(array('description' => "Increases duration of Enduring Melody",'name' => "Enduring Melody Effect Duration"));
Reforge::create(array('description' => "Increases radius of Enduring Melody",'name' => "Enduring Melody Effect Radius"));
Reforge::create(array('description' => "Increases radius of Enduring Melody",'name' => "Enduring Melody Effect Radius"));
Reforge::create(array('description' => "Increases defense increase of Enduring Melody",'name' => "Enduring Melody Defense"));
Reforge::create(array('description' => "Increases defense increase of Enduring Melody",'name' => "Enduring Melody Defense"));
Reforge::create(array('description' => "Increases protection increase of Enduring Melody",'name' => "Enduring Melody Protection"));
Reforge::create(array('description' => "Increases protection increase of Enduring Melody",'name' => "Enduring Melody Protection"));
Reforge::create(array('description' => "Increases mana recovery speed of Enduring Melody",'name' => "Enduring Melody Mana Recovery Speed"));
Reforge::create(array('description' => "Increases mana recovery speed of Enduring Melody",'name' => "Enduring Melody Mana Recovery Speed"));
Reforge::create(array('description' => "Increases stamina recovery speed of Enduring Melody",'name' => "Enduring Melody Stamina Recovery Speed"));
Reforge::create(array('description' => "Increases stamina recovery speed of Enduring Melody",'name' => "Enduring Melody Stamina Recovery Speed"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Enthralling Performance EXP"));
Reforge::create(array('description' => "Increases radius of Enthralling Performance",'name' => "Enthralling Performance Radius Applied"));
Reforge::create(array('description' => "Decreases cooldown time of Enthralling Performance",'name' => "Enthralling Performance Cooldown Decreased"));
Reforge::create(array('description' => "Increases CP limit of Enthralling Performance",'name' => "Enthralling Performance Enthrallment Power Boost"));
Reforge::create(array('description' => "Decreases standby time of Harvest Song",'name' => "Harvest Song Buff Loading Time"));
Reforge::create(array('description' => "Decreases standby time of Harvest Song",'name' => "Harvest Song Buff Loading Time"));
Reforge::create(array('description' => "Increases duration of Harvest Song",'name' => "Harvest Song Duration"));
Reforge::create(array('description' => "Increases duration of Harvest Song",'name' => "Harvest Song Duration"));
Reforge::create(array('description' => "Increases radius of Harvest Song",'name' => "Harvest Song Effect Radius"));
Reforge::create(array('description' => "Increases radius of Harvest Song",'name' => "Harvest Song Effect Radius"));
Reforge::create(array('description' => "Increases gathering speed increase of Harvest Song",'name' => "Harvest Song Gathering Speed"));
Reforge::create(array('description' => "Increases duration of Lullaby",'name' => "Lullaby Duration"));
Reforge::create(array('description' => "Increases duration of Lullaby",'name' => "Lullaby Duration"));
Reforge::create(array('description' => "Increases maximum amount of affected targets of Lullaby",'name' => "Lullaby Max Sleep Targets"));
Reforge::create(array('description' => "Increases maximum amount of affected targets of Lullaby",'name' => "Lullaby Max Sleep Targets"));
Reforge::create(array('description' => "Increases success rate of Lullaby",'name' => "Lullaby Basic Sleep Chance"));
Reforge::create(array('description' => "Increases success rate of Lullaby",'name' => "Lullaby Basic Sleep Chance"));
Reforge::create(array('description' => "Increases additional damage to affected targets(Affects Lullaby's damage, not the offensive skill)",'name' => "Lullaby Bonus Sleep Damage"));
Reforge::create(array('description' => "Increases additional damage to affected targets(Affects Lullaby's damage, not the offensive skill)",'name' => "Lullaby Bonus Sleep Damage"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Playing Instrument EXP"));
Reforge::create(array('description' => "Increases success rate of Playing Instrument",'name' => "Playing Instrument Instrument Playing Success Rate"));
Reforge::create(array('description' => "Increases music buff effect of Playing Instrument",'name' => "Playing Instrument Effect"));
Reforge::create(array('description' => "Increases EXP gained(Has no useful effect...)",'name' => "Musical Knowledge EXP"));
Reforge::create(array('description' => "Increases chance of an excellent performance of music playing-type skills",'name' => "Musical Knowledge Excellent Performance Rate"));
Reforge::create(array('description' => "Increases chance of an excellent performance of music playing-type skills",'name' => "Musical Knowledge Excellent Performance Rate"));
Reforge::create(array('description' => "Increases chance of an inspiring performance of music playing-type skills",'name' => "Musical Knowledge Inspiring Performance Rate"));
Reforge::create(array('description' => "Increases chance of an inspiring performance of music playing-type skills",'name' => "Musical Knowledge Inspiring Performance Rate"));
Reforge::create(array('description' => "Increases music buff effects of normal performances",'name' => "Musical Knowledge Normal Performance Effect"));
Reforge::create(array('description' => "Increases music buff effects of normal performances",'name' => "Musical Knowledge Normal Performance Effect"));
Reforge::create(array('description' => "Increases music buff effects of excellent performances",'name' => "Musical Knowledge Excellent Performance Effect"));
Reforge::create(array('description' => "Increases music buff effects of excellent performances",'name' => "Musical Knowledge Excellent Performance Effect"));
Reforge::create(array('description' => "Increases music buff effects of inspiring performances",'name' => "Musical Knowledge Inspiring Performance Effect"));
Reforge::create(array('description' => "Increases music buff effects of inspiring performances",'name' => "Musical Knowledge Inspiring Performance Effect"));
Reforge::create(array('description' => "Increases duration of Vivace",'name' => "Vivace Duration"));
Reforge::create(array('description' => "Increases duration of Vivace",'name' => "Vivace Duration"));
Reforge::create(array('description' => "Increases magic charging speed increase of Vivace",'name' => "Vivace Magic Charging Speed"));
Reforge::create(array('description' => "Increases magic charging speed increase of Vivace",'name' => "Vivace Magic Charging Speed"));
Reforge::create(array('description' => "Increases alchemy loading speed increase of Vivace",'name' => "Vivace Alchemy Charging Speed"));
Reforge::create(array('description' => "Increases attack speed increase of Vivace",'name' => "Vivace Attack Speed"));
Reforge::create(array('description' => "Increases duration of March Song",'name' => "March Song Duration"));
Reforge::create(array('description' => "Increases radius of March Song",'name' => "March Song Effect Radius"));
Reforge::create(array('description' => "Increases character movement speed increase of March Song",'name' => "March Song Walking Speed"));
Reforge::create(array('description' => "Increases pet movement speed increase of March Song",'name' => "March Song Mount Movement Speed"));
Reforge::create(array('description' => "Increases damage done every second during Puppet's Snare's duration",'name' => "Puppet's Snare Damage Over Time After Stun"));
Reforge::create(array('description' => "Increases duration of Puppet's Snare",'name' => "Puppet's Snare Stun Time"));
Reforge::create(array('description' => "Increases range of Puppet's Snare",'name' => "Puppet's Snare Range"));
Reforge::create(array('description' => "Increases damage of Wire Pull",'name' => "Wire Pull Damage Magnification"));
Reforge::create(array('description' => "Increases range of Wire Pull",'name' => "Wire Pull Range"));
Reforge::create(array('description' => "Increases range of Wire Pull",'name' => "Wire Pull Range"));
Reforge::create(array('description' => "Increases marionette's minimum damage while under control",'name' => "Control Marionette Linked Marionette Min Damage Bonus"));
Reforge::create(array('description' => "Increases marionette's maximum damage while under control",'name' => "Control Marionette Linked Marionette Max Damage Bonus"));
Reforge::create(array('description' => "Increases marionette's critical while under control",'name' => "Control Marionette Linked Marionette Critical Bonus"));
Reforge::create(array('description' => "Increases marionette's balance while under control",'name' => "Control Marionette Linked Marionette Balance Bonus"));
Reforge::create(array('description' => "Increases damage of Inciting Incident",'name' => "Act 1: Inciting Incident Damage Magnification"));
Reforge::create(array('description' => "Increases damage of Inciting Incident",'name' => "Act 1: Inciting Incident Damage Magnification"));
Reforge::create(array('description' => "Increases stun time of Inciting Incident",'name' => "Act 1: Inciting Incident Stun Time"));
Reforge::create(array('description' => "Increases the critical hit rate of Threshold Cutter",'name' => "Act 2: Threshold Cutter Critical Rate Boost"));
Reforge::create(array('description' => "Increases the Damage of Threshold Cutter",'name' => "Act 2: Threshold Cutter Damage Boost"));
Reforge::create(array('description' => "Increases damage of Rising Action",'name' => "Act 4: Rising Action Damage Magnification"));
Reforge::create(array('description' => "Increases damage of Rising Action",'name' => "Act 4: Rising Action Damage Magnification"));
Reforge::create(array('description' => "Increases radius of Rising Action",'name' => "Act 4: Rising Action Radius"));
Reforge::create(array('description' => "Increases radius of Rising Action",'name' => "Act 4: Rising Action Radius"));
Reforge::create(array('description' => "Increases damage of Crisis",'name' => "Act 6: Crisis Damage Magnification"));
Reforge::create(array('description' => "Increases damage of Crisis",'name' => "Act 6: Crisis Damage Magnification"));
Reforge::create(array('description' => "Increases radius of Crisis",'name' => "Act 6: Crisis Radius"));
Reforge::create(array('description' => "Increases radius of Crisis",'name' => "Act 6: Crisis Radius"));
Reforge::create(array('description' => "Decreases loading time of Crisis",'name' => "Act 6: Crisis Casting Time"));
Reforge::create(array('description' => "Increases damage of Climactic Crash",'name' => "Act 7: Climactic Crash Damage Magnification"));
Reforge::create(array('description' => "Increases damage of Climactic Crash",'name' => "Act 7: Climactic Crash Damage Magnification"));
Reforge::create(array('description' => "Increases charge radius of Climactic Crash",'name' => "Act 7: Climactic Crash Charge Width"));
Reforge::create(array('description' => "Decreases loading time of Climactic Crash",'name' => "Act 7: Climactic Crash Casting Time"));
Reforge::create(array('description' => "Increases minimum damage bonus of Invigorating Encore",'name' => "Act 9: Invigorating Encore Initial Min Damage Bonus"));
Reforge::create(array('description' => "Increases minimum damage bonus of Invigorating Encore",'name' => "Act 9: Invigorating Encore Initial Min Damage Bonus"));
Reforge::create(array('description' => "Increases maximum damage bonus of Invigorating Encore",'name' => "Act 9: Invigorating Encore Initial Max Damage Bonus"));
Reforge::create(array('description' => "Increases maximum damage bonus of Invigorating Encore",'name' => "Act 9: Invigorating Encore Initial Max Damage Bonus"));
Reforge::create(array('description' => "Increases duration of Invigorating Encore",'name' => "Act 9: Invigorating Encore Duration"));
Reforge::create(array('description' => "Increases duration of Invigorating Encore",'name' => "Act 9: Invigorating Encore Duration"));
Reforge::create(array('description' => "Increases the damage of act skills",'name' => "Marionette Act Damage Increase"));
Reforge::create(array('description' => "Increases marionette's minimum damage",'name' => "Marionette Minimum Damage"));
Reforge::create(array('description' => "Increases marionette's maximum damage",'name' => "Marionette Maximum Damage"));
Reforge::create(array('description' => "Increases marionette's maximum damage",'name' => "Marionette Maximum Damage"));
Reforge::create(array('description' => "Increases marionette's health",'name' => "Marionette Health"));
Reforge::create(array('description' => "Increases marionette's defense",'name' => "Marionette Defense"));
Reforge::create(array('description' => "Increases marionette's protection",'name' => "Marionette Protection"));
Reforge::create(array('description' => "Increases marionette's magic defense",'name' => "Marionette Magic Defense"));
Reforge::create(array('description' => "Reduces the amount of time necessary to reload",'name' => "Reload Time Reduction"));
Reforge::create(array('description' => "Increases the damage of Flash Launcher",'name' => "Flash Launcher Damage"));
Reforge::create(array('description' => "Increases the damage of Flash Launcher",'name' => "Flash Launcher Damage"));
Reforge::create(array('description' => "Increases the damage of Grapple Shot",'name' => "Grapple Shot Damage"));
Reforge::create(array('description' => "Increases the damage of Grapple Shot",'name' => "Grapple Shot Damage"));
Reforge::create(array('description' => "Increases the damage of Bullet Slide",'name' => "Bullet Slide Damage"));
Reforge::create(array('description' => "Increases the damage of Bullet Slide",'name' => "Bullet Slide Damage"));
Reforge::create(array('description' => "Increases the damage of Shooting Rush",'name' => "Shooting Rush Damage"));
Reforge::create(array('description' => "Increases the damage of Shooting Rush",'name' => "Shooting Rush Damage"));
Reforge::create(array('description' => "Increases the charge width of Shooting Rush",'name' => "Shooting Rush Attack Spread"));
Reforge::create(array('description' => "Increases the charge width of Shooting Rush",'name' => "Shooting Rush Attack Spread"));
Reforge::create(array('description' => "Increases the charge distance of Shooting Rush",'name' => "Shooting Rush Attack Distance"));
Reforge::create(array('description' => "Increases the charge distance of Shooting Rush",'name' => "Shooting Rush Attack Distance"));
Reforge::create(array('description' => "Increases the damage per shot of Bullet Storm",'name' => "Bullet Storm Damage Per Shot"));
Reforge::create(array('description' => "Increases the damage per shot of Bullet Storm",'name' => "Bullet Storm Damage Per Shot"));
Reforge::create(array('description' => "Increases the amount of max targets of Bullet Storm",'name' => "Bullet Storm Max Targets"));
Reforge::create(array('description' => "Increases the radius of Bullet Storm",'name' => "Bullet Storm Attack Spread"));
Reforge::create(array('description' => "Increases the radius of Bullet Storm",'name' => "Bullet Storm Attack Spread"));
Reforge::create(array('description' => "Increases the range of Bullet Storm",'name' => "Bullet Storm Attack Range"));
Reforge::create(array('description' => "Increases the range of Bullet Storm",'name' => "Bullet Storm Attack Range"));
Reforge::create(array('description' => "Increases the maximum damage of Bullet Storm",'name' => "Bullet Storm Maximum Damage"));
Reforge::create(array('description' => "Increases the duration of Way of the Gun",'name' => "Way of the Gun Duration"));
Reforge::create(array('description' => "Increases the Way of the Gun attack speed bonus",'name' => "Way of the Gun Attack Speed"));
Reforge::create(array('description' => "Increases strength while in Dark Knight transformation",'name' => "Body of Chaos [Transforming] STR"));
Reforge::create(array('description' => "Increases duration of Control of Darkness",'name' => "Control of Darkness Duration"));
Reforge::create(array('description' => "Increases injury rate while in Dark Knight transformation",'name' => "Hands of Chaos [Transforming] Injury Rate"));
Reforge::create(array('description' => "Increases dexterity while in Dark Knight transformation",'name' => "Hands of Chaos [Transforming] DEX"));
Reforge::create(array('description' => "Increases critical while in Dark Knight transformation",'name' => "Mind of Chaos [Transforming] Critical"));
Reforge::create(array('description' => "Increases intelligence while in Dark Knight transformation",'name' => "Mind of Chaos [Transforming] INT"));
Reforge::create(array('description' => "Increases stamina while in Dark Knight transformation",'name' => "Soul of Chaos [Transforming] Max Stamina"));
Reforge::create(array('description' => "Increases HP while in Dark Knight transformation(Despite the reforge name, it actually affects HP rather than strength)",'name' => "Soul of Chaos [Transforming] STR"));
Reforge::create(array('description' => "Increases mana while in Dark Knight transformation",'name' => "Soul of Chaos [Transforming] Max MP"));
Reforge::create(array('description' => "Increases duration of Dark Knight transformation",'name' => "Soul of Chaos Duration"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Soul of Chaos EXP"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Awakening of Light EXP"));
Reforge::create(array('description' => "Decreases cooldown time of Awakening of Light",'name' => "Awakening of Light Cooldown Decreased"));
Reforge::create(array('description' => "Increases range of Fury of Light",'name' => "Fury of Light Attack Range"));
Reforge::create(array('description' => "Increases damage of Fury of Light",'name' => "Fury of Light Damage"));
Reforge::create(array('description' => "Decreases cooldown time of Fury of Light",'name' => "Fury of Light Cooldown Decreased"));
Reforge::create(array('description' => "Increases damage of Shadow Spirit",'name' => "Shadow Spirit Damage"));
Reforge::create(array('description' => "Increases range of Spear of Light",'name' => "Spear of Light Range"));
Reforge::create(array('description' => "Increases blast radius of Spear of Light",'name' => "Spear of Light Explosion Radius"));
Reforge::create(array('description' => "Decreases cooldown time of Wings of Eclipse",'name' => "Wings of Eclipse Cooldown Decreased"));
Reforge::create(array('description' => "Increases damage of Wings of Range",'name' => "Wings of Rage Damage"));
Reforge::create(array('description' => "Increases range of Wings of Rage",'name' => "Wings of Rage Range"));
Reforge::create(array('description' => "Increases linear radius of Wings of Rage(Despite the reforge name, it affects linear radius rather than attack range)",'name' => "Wings of Rage Attack Range"));
Reforge::create(array('description' => "Decreases cooldown time of Wings of Rage",'name' => "Wings of Rage Cooldown Reduction"));
Reforge::create(array('description' => "Increases protection while in Falcon transformation",'name' => "Armor of Connous [Transforming] Protection"));
Reforge::create(array('description' => "Increases will while in Falcon transformation",'name' => "Armor of Connous [Transforming] Will"));
Reforge::create(array('description' => "Increases defense while in Falcon transformation",'name' => "Armor of Connous [Transforming] Defense"));
Reforge::create(array('description' => "Increases wand damage of Elven Magic Missile",'name' => "Elven Magic Missile Magic Damage"));
Reforge::create(array('description' => "Increases bow damage of Elven Magic Missile",'name' => "Elven Magic Missile Ranged Attack Damage"));
Reforge::create(array('description' => "Increases maximum injury rate while in Falcon transformation",'name' => "Fury of Connous [Transforming] Max Injury Rate"));
Reforge::create(array('description' => "Increases minimum injury rate while in Falcon transformation",'name' => "Fury of Connous [Transforming] Min Injury Rate"));
Reforge::create(array('description' => "Increases duration of Falcon transformation",'name' => "Fury of Connous Duration"));
Reforge::create(array('description' => "Increases maximum damage while in Falcon transformation",'name' => "Fury of Connous [Transforming] Max Damage"));
Reforge::create(array('description' => "Increases HP while in Falcon transformation",'name' => "Fury of Connous [Transforming] Max HP Amplify"));
Reforge::create(array('description' => "Increases stamina while in Falcon transformation",'name' => "Fury of Connous [Transforming] Max Stamina"));
Reforge::create(array('description' => "Increases minimum damage while in Falcon transformation",'name' => "Fury of Connous [Transforming] Min Damage"));
Reforge::create(array('description' => "Increases strength while in Falcon transformation",'name' => "Fury of Connous [Transforming] STR"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Fury of Connous EXP"));
Reforge::create(array('description' => "Increases mana while in Falcon transformation",'name' => "Mind of Connous [Transforming] Max MP"));
Reforge::create(array('description' => "Increases intelligence while in Falcon transformation",'name' => "Mind of Connous [Transforming] INT"));
Reforge::create(array('description' => "Increases dexterity while in Falcon transformation",'name' => "Sharpness of Connous [Transforming] DEX"));
Reforge::create(array('description' => "Increases critical while in Falcon transformation",'name' => "Sharpness of Connous [Transforming] Critical"));
Reforge::create(array('description' => "Increases dexterity while in Paladin transformation",'name' => "Eye of Order [Transforming] DEX"));
Reforge::create(array('description' => "Increases will while in Paladin transformation",'name' => "Power of Order [Transforming] Will"));
Reforge::create(array('description' => "Increases strength while in Paladin transformation",'name' => "Power of Order [Transforming] STR"));
Reforge::create(array('description' => "Increases duration of Paladin transformation",'name' => "Spirit of Order Duration"));
Reforge::create(array('description' => "Increases mana while in Paladin transformation",'name' => "Spirit of Order [Transforming] Max MP"));
Reforge::create(array('description' => "Increases health while in Paladin transformation",'name' => "Spirit of Order [Transforming] Max HP"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Spirit of Order EXP"));
Reforge::create(array('description' => "Increases defense while in Paladin transformation",'name' => "Spirit of Order [Transforming] Defense"));
Reforge::create(array('description' => "Increases protection while in Paladin transformation",'name' => "Spirit of Order [Transforming] Protection"));
Reforge::create(array('description' => "Increases stamina while in Paladin transformation",'name' => "Spirit of Order [Transforming] Max Stamina"));
Reforge::create(array('description' => "Increases injury rate while in Paladin transformation",'name' => "Sword of Order [Transforming] Injury Rate"));
Reforge::create(array('description' => "Increases damage while in Paladin transformation",'name' => "Sword of Order [Transforming] Damage"));
Reforge::create(array('description' => "Increases duration of Beast transformation",'name' => "Daemon of Physis Duration"));
Reforge::create(array('description' => "Increases maximum damage while in Beast transformation",'name' => "Daemon of Physis [Transforming] Max Damage"));
Reforge::create(array('description' => "Increases minimum damage while in Beast transformation",'name' => "Daemon of Physis [Transforming] Min Damage"));
Reforge::create(array('description' => "Increases EXP gained",'name' => "Daemon of Physis EXP"));
Reforge::create(array('description' => "Increases damage with non-Two-Handed Blunt Weapons of Giant Full Swing",'name' => "Giant Full Swing Damage"));
Reforge::create(array('description' => "Increases damage with Two-Handed Blunt Weapons of Giant Full Swing",'name' => "Giant Full Swing Exclusive Weapon Damage"));
Reforge::create(array('description' => "Increases range with non-Two-Handed Blunt Weapons of Giant Full Swing",'name' => "Giant Full Swing Attack Range"));
Reforge::create(array('description' => "Increases range with Two-Handed Blunt Weapons of Giant Full Swing",'name' => "Giant Full Swing Exclusive Weapon Range"));
Reforge::create(array('description' => "Increases stamina while in Beast transformation",'name' => "Life of Physis [Transforming] Stamina"));
Reforge::create(array('description' => "Increases will while in Beast transformation",'name' => "Life of Physis [Transforming] Will"));
Reforge::create(array('description' => "Increases strength while in Beast transformation",'name' => "Life of Physis [Transforming] STR"));
Reforge::create(array('description' => "Increases defense while in Beast transformation",'name' => "Shield of Physis [Transforming] Defense"));
Reforge::create(array('description' => "Increases protection while in Beast transformation",'name' => "Shield of Physis [Transforming] Protection"));
Reforge::create(array('description' => "Increases health while in Beast transformation",'name' => "Shield of Physis [Transforming] Max HP"));
Reforge::create(array('description' => "Increases intelligence while in Beast transformation",'name' => "Spell of Physis [Transforming] INT"));
Reforge::create(array('description' => "Increases critical while in Beast transformation",'name' => "Spell of Physis [Transforming] Critical"));
Reforge::create(array('description' => "Increases mana while in Beast transformation",'name' => "Spell of Physis [Transforming] Max MP"));
Reforge::create(array('description' => "Increases chance of activating Melee Auto Defense",'name' => "Auto Melee Defense"));
Reforge::create(array('description' => "Increases chance of activating Magic Auto Defense",'name' => "Auto Magic Defense"));
Reforge::create(array('description' => "Increases chance of activating Ranged Auto Defense",'name' => "Auto Range Defense"));
Reforge::create(array('description' => "",'name' => "Critical Hit EXP"));
Reforge::create(array('description' => "Increases Attack Speed Set Effect(10 points required for effect)",'name' => "Attack Speed"));
Reforge::create(array('description' => "Increases Attack Speed Set Effect(10 points required for effect)",'name' => "Attack Speed"));
Reforge::create(array('description' => "Increases Explosion Defense Set Effect(10 points required for effect)",'name' => "Explosion Defense"));
Reforge::create(array('description' => "Increases Poison Immunity Set Effect(10 points required for effect)",'name' => "Poison Immunity"));
Reforge::create(array('description' => "Increases Petrification Immunity Set Effect(10 points required for effect)",'name' => "Petrification Immunity"));
Reforge::create(array('description' => "Increases Stomp Defense Set Effect(10 points required for effect)",'name' => "Stomp Defense"));
Reforge::create(array('description' => "Increases HP",'name' => "Maximum Health Increase"));
Reforge::create(array('description' => "Increases MP",'name' => "Maximum Mana Increase"));
Reforge::create(array('description' => "Increases stamina",'name' => "Maximum Stamina Increase"));
Reforge::create(array('description' => "Increases strength",'name' => "Strength Increase"));
Reforge::create(array('description' => "Increases intelligence",'name' => "Intelligence Increase"));
Reforge::create(array('description' => "Increases dexterity",'name' => "Dexterity Increase"));
Reforge::create(array('description' => "Increases will",'name' => "Will Increase"));
Reforge::create(array('description' => "Increases luck",'name' => "Luck Increase"));
Reforge::create(array('description' => "Increases critical hit chance",'name' => "Critical"));
Reforge::create(array('description' => "Increases balance",'name' => "Balance Increase"));
Reforge::create(array('description' => "Increases defense",'name' => "Defense Increase"));
Reforge::create(array('description' => "Increases protection",'name' => "Protection Increase"));
Reforge::create(array('description' => "Increases minimum damage(Does not affect magic attack)",'name' => "Min Attack Power"));
Reforge::create(array('description' => "Increases maximum damage(Does not affect magic attack)",'name' => "Max Attack Power"));
Reforge::create(array('description' => "Increases maximum damage(Does not affect magic attack)",'name' => "Max Attack Power"));
Reforge::create(array('description' => "Increases minimum damage while Dual Guns are equipped",'name' => "Dual Gun Minimum Damage"));
Reforge::create(array('description' => "Increases maximum damage while Dual Guns are equipped",'name' => "Dual Gun Maximum Damage"));
Reforge::create(array('description' => "Increases minimum injury rate",'name' => "Minimum Injury Rate"));
Reforge::create(array('description' => "Increases maximum injury rate",'name' => "Maximum Injury Rate"));
Reforge::create(array('description' => "Increases magic attack",'name' => "Magic Attack"));
Reforge::create(array('description' => "Increases casting speed",'name' => "Casting Speed"));
Reforge::create(array('description' => "Increases range of ranged skills",'name' => "Effective Range"));
Reforge::create(array('description' => "Increases chance of gathering a 2nd item",'name' => "Gathering Bonus"));
Reforge::create(array('description' => "Increases gathering speed",'name' => "Gathering Speed"));
Reforge::create(array('description' => "Increases gathering success rate",'name' => "Gathering Success Rate"));
Reforge::create(array('description' => "Increases damage done on neutral, ice, and lightning-type monsters. Decreases damage done on fire-type monsters.1-handed weapons limit",'name' => "Fire"));
Reforge::create(array('description' => "Increases damage done on neutral, fire, and lightning-type monsters. Decreases damage done on ice-type monsters.1-handed weapons limit",'name' => "Ice"));
Reforge::create(array('description' => "Increases damage done on neutral, ice, and fire-type monsters. Decreases damage done on lightning-type monsters.1-handed weapons limit",'name' => "Lightning"));
Reforge::create(array('description' => "Increases efficiency of Wind-type alchemy",'name' => "Wind Alchemy"));
Reforge::create(array('description' => "Increases efficiency of Water-type alchemy",'name' => "Water Alchemy"));
Reforge::create(array('description' => "Increases efficiency of Earth-type alchemy",'name' => "Earth Alchemy"));
Reforge::create(array('description' => "Increases efficiency of Fire-type alchemy",'name' => "Fire Alchemy"));
Reforge::create(array('description' => "Increases speed during commerce. Antonio's, Bassanio's, Portia's, and Shylock's Costume (G15) can reach higher levels.",'name' => "Commerce Speed"));
Reforge::create(array('description' => "Increases maximum durability of the reforged item",'name' => "Equipment Max Durability"));
Reforge::create(array('description' => "Increases L-Rod Exploration Range",'name' => "Exploration Range"));
Reforge::create(array('description' => "Increases movement speedMaximum level of 5",'name' => "Movement Speed Increase"));

	}
}